SELECT
    a.EPISODE_ID_TABLE_ADMISSIONS AS EPISODE_ID,
    a.MRN_TABLE_ADMISSIONS AS MRN,
    l.NAME_TABLE_LOCATIONS AS FACILITY,
    a.PROGRAM_TABLE_ADMISSIONS AS PROGRAM,
    a.FNAME_TABLE_ADMISSIONS AS FIRST_NAME,
    a.LNAME_TABLE_ADMISSIONS AS LAST_NAME,
    a.DATEDISCHARGE_TABLE_ADMISSIONS AS DISCHARGE_DATE,
    a.DCTYPE_TABLE_ADMISSIONS AS DISCHARGE_TYPE,
    a.DCREASON_TABLE_ADMISSIONS AS DISCHARGE_REASON,
    c.PAYOR_TABLE_CENSUS AS PAYOR,
    c.PRICOUNS_TABLE_CENSUS AS CLINICIAN
FROM PRECOG.LS_CENSUS_ADMISSIONS_EPISODE_LIGHTNING_STEP_OAC.TABLE_ADMISSIONS a
LEFT JOIN PRECOG.LS_ATTENDANCE_LIGHTNING_STEP_OAC.TABLE_LOCATIONS l
    ON a.LOCATION_ID_TABLE_ADMISSIONS = l.ID_TABLE_LOCATIONS
LEFT JOIN PRECOG.LS_CENSUS_ADMISSIONS_EPISODE_LIGHTNING_STEP_OAC.TABLE_CENSUS c
    ON a.EPISODE_ID_TABLE_ADMISSIONS = c.EPISODE_ID_TABLE_CENSUS
WHERE a.FNAME_TABLE_ADMISSIONS IS NOT NULL
  AND a.DCTYPE_TABLE_ADMISSIONS <> 'Transfer'
  AND a.EIE_TABLE_ADMISSIONS <> 1
  AND a.FNAME_TABLE_ADMISSIONS NOT ILIKE '%Test%'
  AND a.LNAME_TABLE_ADMISSIONS NOT ILIKE '%Test%'
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY a.EPISODE_ID_TABLE_ADMISSIONS
    ORDER BY a.DATEDISCHARGE_TABLE_ADMISSIONS DESC
) = 1