with 

source as (

    select * from {{ source('lightning_step_census_admissions', 'table_census') }}

),

renamed as (

    select
        accruedamount_table_census as accruedamount,
        admission_id_table_census as admission_id,
        age_table_census as age,
        alias_table_census as alias,
        astatus_luby_id_table_census as astatus_luby_id,
        astatus_table_census as astatus,
        authorizedamount_table_census as authorizedamount,
        bed_id_table_census as bed_id,
        bednumber_table_census as bednumber,
        billedamount_table_census as billedamount,
        chargekey_table_census as chargekey,
        client_id_table_census as client_id,
        created_at_table_census as created_at,
        dateagencyadmission_table_census as dateagencyadmission,
        datedc_table_census as datedc,
        datedoc_table_census as datedoc,
        datepgmadmission_table_census as datepgmadmission,
        dateprojdc_table_census as dateprojdc,
        datereview_table_census as datereview,
        dayspresent_table_census as dayspresent,
        dctype_id_table_census as dctype_id,
        dob_table_census as dob,
        dom_table_census as dom,
        doy_table_census as doy,
        dtastatus_table_census as dtastatus,
        eie_table_census as eie,
        episode_id_table_census as episode_id,
        flagcolor_table_census as flagcolor,
        flags_table_census as flags,
        fname_table_census as fname,
        fnamelname_table_census as fnamelname,
        gender_table_census as gender,
        id_table_census as id,
        inquiry_id_table_census as inquiry_id,
        isallergy_table_census as isallergy,
        isauthorized_table_census as isauthorized,
        isautocharge_table_census as isautocharge,
        isbillable_table_census as isbillable,
        ischarged_table_census as ischarged,
        iscovered_table_census as iscovered,
        isdc_table_census as isdc,
        isflag_table_census as isflag,
        ispending_table_census as ispending,
        issupplemental_table_census as issupplemental,
        lname_table_census as lname,
        lnamefname_table_census as lnamefname,
        location_id_table_census as location_id,
        location_table_census as location,
        mname_table_census as mname,
        mo_table_census as mo,
        mrn_table_census as mrn,
        noauthrequired_table_census as noauthrequired,
        nonbillableamount_table_census as nonbillableamount,
        payor_table_census as payor,
        payortype_table_census as payortype,
        pgm_id_table_census as pgm_id,
        pgmname_table_census as pgmname,
        precog_delta_key_table_census as precog_delta_key,
        pricouns_table_census as pricouns,
        pridxcode_table_census as pridxcode,
        rate_table_census as rate,
        reforg_table_census as reforg,
        refperson_table_census as refperson,
        refsrc_table_census as refsrc,
        room_id_table_census as room_id,
        roomnumber_table_census as roomnumber,
        sessionsauth_table_census as sessionsauth,
        sessionsgroup_table_census as sessionsgroup,
        sessionsind_table_census as sessionsind,
        staff_id_table_census as staff_id,
        status_table_census as status,
        table_census_precog_key,
        unit_id_table_census as unit_id,
        unitname_table_census as unitname,
        updated_at_table_census as updated_at,
        yr_table_census as yr,
        precog_delta_version_table_census as precog_delta_version

    from source

)

select * from renamed